export const getCuentas = () => {
    return [
      { id: '01', name: 'AJE' },
      { id: '02', name: 'ALICORP S.A.A' },
      { id: '03', name: 'AMNISTIA INTERNACIONAL' },
      { id: '04', name: 'BANBIF' },
      { id: '05', name: 'BANCO CONTINENTAL' },
      { id: '06', name: 'BANCO GNB PERÚ S.A.' },
      { id: '07', name: 'BANCO RIPLEY' },
      { id: '08', name: 'BERLITZ' },
      { id: '09', name: 'BRITISH TELECOM' },
      { id: '10', name: 'CALIDDA' },
      { id: '11', name: 'CENCOSUD'},
      { id: '12', name: 'CENCOSUD MDH'},
      { id: '13', name: 'CLARO CHILE'},
      { id: '14', name: 'CLARO PERÚ'},
      { id: '15', name: 'CLINICA SAN JUAN DE DIOS'},
      { id: '16', name: 'DERRAMA MAGISTERIAL'},
      { id: '17', name: 'DINERS'},
      { id: '18', name: 'ENTEL'},
      { id: '19', name: 'ENTEL PERÚ'},
      { id: '20', name: 'FARMACIA VECINA'},
      { id: '21', name: 'INNOVA SCHOOL'},
      { id: '22', name: 'KREALO'},
      { id: '23', name: 'LATAM'},
      { id: '24', name: 'MOVISTAR ARGENTINA'},
      { id: '25', name: 'MOVISTAR CHILE'},
      { id: '26', name: 'MOVISTAR PERÚ'},
      { id: '27', name: 'ONCOSALUD'},
      { id: '28', name: 'ONO'},
      { id: '29', name: 'PACÍFICO'},
      { id: '30', name: 'RÍMAC'},
      { id: '31', name: 'SANTANDER CONSUMO PERÚ S.A.'},
      { id: '32', name: 'UNICEF'},
      { id: '33', name: 'UNIQUE'},
      { id: '34', name: 'VODAFONE'},
      { id: '35', name: 'SUNAT'},
      { id: '36', name: 'YAMBAL'},
      { id: '37', name: 'DRIMER'},

      
    ];
  }

  export const getServicios = () => {
    return [
      { id: '0101', name: 'ATENCIÓN AL CLIENTE', idCuenta: '01' },
      { id: '0102', name: 'REDES SOCIALES', idCuenta: '01' },
      { id: '0201', name: 'ALICORP BACK OFFICE', idCuenta: '02' },
      { id: '0202', name: 'ALICORP VENTAS', idCuenta: '02' },
      { id: '0203', name: 'REDES SOCIALES', idCuenta: '02' },
      { id: '0204', name: 'WHATSAPP', idCuenta: '02' },
      { id: '0301', name: 'CAPTACION DE SOCIOS', idCuenta: '03' },
      { id: '0401',name: 'COMPRA DE DEUDA',idCuenta: '04'},
      { id: '0402',name: 'PERSONAS',idCuenta: '04'},
      { id: '0403',name: 'RECLAMOS',idCuenta: '04'},
      { id: '0404',name: 'RETENCIONES',idCuenta: '04'},
      { id: '0405',name: 'TARJETA DE CRÉDITO',idCuenta: '04'},
      { id: '0501',name: 'PRESTAMOS DE LIBRE DISPONIBILIDAD',idCuenta: '05'},
      { id: '0601',name: 'GNB ATENCIÓN AL CLIENTE',idCuenta: '06'},
      { id: '0602',name: 'GNB INTERNET',idCuenta: '06'},
      { id: '0603',name: 'GNB TELEMARKETING',idCuenta: '06'},
      { id: '0701',name: 'TELEVENTAS TC',idCuenta: '07'},
      { id: '0801',name: 'ATENCIÓN BERLITZ',idCuenta: '08'},
      { id: '0802',name: 'VENTA CONSULTIVA',idCuenta: '08'},
      { id: '0901',name: 'BRITISH SERVICE DESK CORPORATE',idCuenta: '09'},
      { id: '0902',name: 'BRITISH SERVICE DESK PYMES',idCuenta: '09'},
      { id: '0903',name: 'BRITISH TELECOM',idCuenta: '09'},
      { id: '1001',name: 'ATENCIÓN AL CLIENTE',idCuenta: '10'},
      { id: '1002',name: 'EMERGENCIA ATC',idCuenta: '10'},
      { id: '1003',name: 'PRESENCIAL',idCuenta: '10'},
      { id: '1004',name: 'TELEVENTAS',idCuenta: '10'},
      { id: '1101',name: 'CHAT',idCuenta: '11'},
      { id: '1102',name: 'FONOCOMPRAS',idCuenta: '11'},
      { id: '1103',name: 'POSTVENTA',idCuenta: '11'},
      { id: '1104',name: 'REDES',idCuenta: '11'},
      { id: '1105',name: 'WHATSAPP',idCuenta: '11'},
      { id: '1201',name: 'CENCOSUD MDH CONSULTAS',idCuenta: '12'},
      { id: '1202',name: 'CENCOSUD MDH REDES SOCIALES',idCuenta: '12'},
      { id: '1203',name: 'CENCOSUD MDH VENTAS INBOUND',idCuenta: '12'},
      { id: '1301',name: 'BACKOFFICE',idCuenta: '13'},
      {  id: '1302',name: 'CAPTACIONES MOVIL',idCuenta: '13'},
      { id: '1303',name: 'DTH',idCuenta: '13'},
      { id: '1304',name: 'HFC',idCuenta: '13'},
      { id: '1305',name: 'MOVIL',idCuenta: '13'},
      { id: '1306',name: 'POSTPAGO',idCuenta: '13'},
      { id: '1307',name: 'PREPAGO',idCuenta: '13'},
      { id: '1308',name: 'RETENCIONES HOGAR',idCuenta: '13'},
      { id: '1401',name: 'AFILIACIÓN',idCuenta: '14'},
      { id: '1402',name: 'EMPRESAS',idCuenta: '14'},
      { id: '1403',name: 'MANTENIMIENTO',idCuenta: '14'},
      { id: '1404',name: 'MANTENIMIENTO RENOVACIÓN',idCuenta: '14'},
      { id: '1405',name: 'MASIVO',idCuenta: '14'},
      { id: '1501',name: 'ATENCION AL CLIENTE',idCuenta: '15'},
      { id: '1601',name: 'DERRAMA MAGISTERIAL TELEMARKETING',idCuenta: '16'},
      { id: '1701',name: 'ATENCIÓN AL CLIENTE',idCuenta: '17'},
      { id: '1702',name: 'CHAT',idCuenta: '17'},
      { id: '1703',name: 'REDES SOCIALES',idCuenta: '17'},
      { id: '1704',name: 'UNIDAD TIPO DE CAMBIO',idCuenta: '17'},
      { id: '1705',name: 'VENTAS',idCuenta: '17'},
      { id: '1801',name: 'C2C',idCuenta: '18'},
      { id: '1802',name: 'CROSSELING',idCuenta: '18'},
      { id: '1803',name: 'FONOCOMPRAS HOGAR',idCuenta: '18'},
      { id: '1804',name: 'FONOCOMPRAS MOVIL',idCuenta: '18'},
      { id: '1805',name: 'HOME',idCuenta: '18'},
      { id: '1806',name: 'MIGRACIONES',idCuenta: '18'},
      { id: '1807',name: 'PORTABILIDAD',idCuenta: '18'},
      { id: '1808',name: 'POSTPAGO MASIVO',idCuenta: '18'},
      { id: '1809',name: 'REDES SOCIALES',idCuenta: '18'},
      { id: '1810',name: 'S2S HOGAR',idCuenta: '18'},
      { id: '1811',name: 'S2S MOVIL',idCuenta: '18'},
      { id: '1812',name: 'WEB HOGAR',idCuenta: '18'},
      { id: '1813',name: 'WEB MOVIL',idCuenta: '18'},
      { id: '1814',name: 'WHATSAPP',idCuenta: '18'},
      { id: '1901',name: 'BACK OFFICE',idCuenta: '19'},
      { id: '1902',name: 'BIENVENIDA',idCuenta: '19'},
      { id: '1903',name: 'BIENVENIDA EMPRESAS',idCuenta: '19'},
      { id: '1904',name: 'CANALES DIGITALES TLV',idCuenta: '19'},
      { id: '1905',name: 'CONTRABLINDAJE BONO',idCuenta: '19'},
      { id: '1906',name: 'CONTRABLINDAJE RENOVACIÓN',idCuenta: '19'},
      { id: '1907',name: 'DIRECTORIO Y BLOQUEO',idCuenta: '19'},
      { id: '1908',name: 'FRONT HOGAR',idCuenta: '19'},
      { id: '1909',name: 'HOGAR BO',idCuenta: '19'},
      { id: '1910',name: 'MIGRACIONES',idCuenta: '19'},
      { id: '1911',name: 'NPS',idCuenta: '19'},
      { id: '1912',name: 'PILOTO EMPRESAS',idCuenta: '19'},
      { id: '1913',name: 'PLATINO',idCuenta: '19'},
      { id: '1914',name: 'PORTABILIDAD',idCuenta: '19'},
      { id: '1915',name: 'POSTPAGO',idCuenta: '19'},
      { id: '1916',name: 'POSTPAGO ORO',idCuenta: '19'},
      { id: '1917',name: 'PREPAGO',idCuenta: '19'},
      { id: '1918',name: 'REDES SOCIALES',idCuenta: '19'},
      { id: '1919',name: 'RENOVACION DE EQUIPOS',idCuenta: '19'},
      { id: '1920',name: 'RENOVACION PROACTIVA',idCuenta: '19'},
      { id: '1921',name: 'TELEVENTAS EMPRESAS',idCuenta: '19'},
      { id: '1922',name: 'UPSELLING',idCuenta: '19'},
      { id: '1923',name: 'WHATSAPP EMPRESAS',idCuenta: '19'},
      { id: '1924',name: 'WHATSAPP HOGAR',idCuenta: '19'},
      { id: '1925',name: 'WHATSAPP MULTISKILL',idCuenta: '19'},
      { id: '1926',name: 'WHATSAPP EMPRESAS',idCuenta: '19'},
      { id: '1927',name: 'WHATSAPP S2S',idCuenta: '19'},
      { id: '1928',name: 'MULTISKILL',idCuenta: '19'},
      { id: '1929',name: 'RETENCIÓN HOGAR',idCuenta: '19'},
      { id: '1930',name: 'VENTA DIGITAL EMPRESAS',idCuenta: '19'}, 
      { id: '1931',name: 'REDES SOCIALES (PARTE PRIVADA)',idCuenta: '19'}, 
      { id: '1932',name: 'WHATSAPP MULTISKILL VENTAS',idCuenta: '19'}, 
      { id: '1933',name: 'WHATSAPP MULTISKILL POST',idCuenta: '19'}, 
      { id: '2020',name: 'ATENCIÓN AL CLIENTE',idCuenta: '20'},
      { id: '2021',name: 'FIELDMARKETING',idCuenta: '20'},
      { id: '2101',name: 'ATENCION AL CLIENTE',idCuenta: '21'},
      { id: '2102',name: 'VENTAS',idCuenta: '21'},
      { id: '2202',name: 'CULQUI',idCuenta: '22'},
      { id: '2301',name: 'LATAM CARGO',idCuenta: '23'},
      { id: '2302',name: 'LAN PASS',idCuenta: '23'},
      { id: '2303',name: 'LAN PASS UNIFICADO',idCuenta: '23'},
      { id: '2304',name: 'LATAM CARGO',idCuenta: '23'},
      { id: '2305',name: 'LATAM CARGO BILINGUE',idCuenta: '23'},
      { id: '2306',name: 'MULTISKILL BILINGUE',idCuenta: '23'},
      { id: '2401',name: '1L ESPECIALISTA CROSSELING',idCuenta: '24'},
      { id: '2402',name: '1L MOVIL COMERCIAL',idCuenta: '24'},
      { id: '2403',name: '1L TÉCNICA',idCuenta: '24'},
      { id: '2404',name: 'BLENDING',idCuenta: '24'},
      { id: '2405',name: 'BLENDING IN',idCuenta: '24'},
      { id: '2406',name: 'C2C',idCuenta: '24'},
      { id: '2407',name: 'CAMBIO DE PLAN',idCuenta: '24'},
      { id: '2409',name: 'CAMBIO DE PLAN PXQ',idCuenta: '24'},
      { id: '2410',name: 'CASIM',idCuenta: '24'},
      { id: '2411',name: 'CATER OUT',idCuenta: '24'},
      { id: '2412',name: 'FIDELIZACIÓN',idCuenta: '24'},
      { id: '2413',name: 'MIGRACIONES OUT',idCuenta: '24'},
      { id: '2415',name: 'PORTABILIDAD',idCuenta: '24'},
      { id: '2416',name: 'PRIMERAS LINEAS INTEGRADA',idCuenta: '24'},
      { id: '2417',name: 'REDES SOCIALES',idCuenta: '24'},
      { id: '2418',name: 'REPO POR ROBO',idCuenta: '24'},
      { id: '2419',name: 'TELEVENTAS IN',idCuenta: '24'},
      { id: '2420',name: 'CROSSELING',idCuenta: '24'},
      { id: '2501',name: 'BELIEVE',idCuenta: '25'},
      { id: '2502',name: 'CANAL WEB',idCuenta: '25'},
      { id: '2503',name: 'FIJA MASIVO',idCuenta: '25'},
      { id: '2504',name: 'TCH VENTAS FIJA',idCuenta: '25'},
      { id: '2505',name: 'TCH VENTAS MÓVIL',idCuenta: '25'},
      { id: '2601',name: 'CORTE POR ROBO',idCuenta: '26'},
      { id: '2602',name: 'CROSSELING FIJA',idCuenta: '26'},
      { id: '2603',name: 'CROSSELING MÓVIL',idCuenta: '26'},
      { id: '2604',name: 'REDES SOCIALES',idCuenta: '26'},
      { id: '2605',name: 'RESINDECIAL FIJA',idCuenta: '26'},
      { id: '2607',name: 'RETENCIÓN NEGOCIOS IN',idCuenta: '26'},
      { id: '2608',name: 'RETENCIÓN NEGOCIOS OUT',idCuenta: '26'},
      { id: '2609',name: 'RETENCIONES CONVERGENTE',idCuenta: '26'},
      { id: '2610',name: 'RETENCIONES FIJA',idCuenta: '26'},
      { id: '2611',name: 'RETENCIONES MÓVILES',idCuenta: '26'},
      { id: '2612',name: 'TÉCNICA FIJA',idCuenta: '26'},
      { id: '2613',name: 'WHATSAPP',idCuenta: '26'},
      { id: '2614',name: 'WHATSAPP CROSSELING',idCuenta: '26'},
      { id: '2615',name: 'WHATSAPP RETENCIÓN MT',idCuenta: '26'},
      { id: '2616',name: 'WHATSAPP RETENCIONES FIJA',idCuenta: '26'},
      { id: '2617',name: 'WHATSAPP RETENCIÓN MÓVIL',idCuenta: '26'},
      { id: '2618',name: 'WHATSAPP TÉCNICA FIJA',idCuenta: '26'},
      { id: '2701',name: 'REDES SOCIALES',idCuenta: '27'},
      { id: '2702',name: 'ADMINISTRACIÓN DE MARCA AUNA Y RED DE CLINICAS',idCuenta: '27'},
      { id: '2801',name: 'CARTERA',idCuenta: '28'},
      { id: '2802',name: 'ONO AVERIAS',idCuenta: '28'},
      { id: '2803',name: 'ONO PROVISIONES',idCuenta: '28'},
      { id: '2901',name: 'MULTISKILL',idCuenta: '29'},
      { id: '2902',name: 'ONCOLOGICO',idCuenta: '29'},
      { id: '2903',name: 'ONCOLOGICO VIDA',idCuenta: '29'},
      { id: '2904',name: 'OTROS SEGUROS',idCuenta: '29'},
      { id: '2905',name: 'REDES SOCIALES',idCuenta: '29'},
      { id: '2907',name: 'RETENCIONES',idCuenta: '29'},
      { id: '2908',name: 'SALUD',idCuenta: '29'},
      { id: '2909',name: 'SINIESTROS',idCuenta: '29'},
      { id: '2910',name: 'VIDA',idCuenta: '29'},
      { id: '2911',name: 'AUXILIO MÉDICO',idCuenta: '29'},
      { id: '3001',name: 'CLINICAS',idCuenta: '30'},
      { id: '3002',name: 'CORREDORES',idCuenta: '30'},
      { id: '3003',name: 'DELIVERY MEDICINA',idCuenta: '30'},
      { id: '3004',name: 'INSPECCIONES',idCuenta: '30'},
      { id: '3005',name: 'ONCOLOGICO',idCuenta: '30'},
      { id: '3007',name: 'ONCOLOGICO IN',idCuenta: '30'},
      { id: '3008',name: 'PROTECCION MULTIPLE',idCuenta: '30'},
      { id: '3009',name: 'RENTA HOSPITALARIA',idCuenta: '30'},
      { id: '3010',name: 'RETENCIONES',idCuenta: '30'},
      { id: '3011',name: 'RIMAC BACK OFFICE BROKER',idCuenta: '30'},
      { id: '3012',name: 'SALUD',idCuenta: '30'},
      { id: '3013',name: 'SEGURO SALUD',idCuenta: '30'},
      { id: '3014',name: 'VEHICULAR BBVA',idCuenta: '30'},
      { id: '3015',name: 'VEHICULAR IBK',idCuenta: '30'},
      { id: '3016',name: 'VIDA RENTA OUT',idCuenta: '30'},
      { id: '3017',name: 'WELCOME PROTECCION TARJETA',idCuenta: '30'},
      { id: '3018',name: 'WELCOME VEHICULAR',idCuenta: '30'},
      { id: '3019',name: 'CONSULTAS CLÍNICAS Y SALUD',idCuenta: '30'},
      { id: '3020',name: 'RETENCIONES BBVA',idCuenta: '30'},
      { id: '3101',name: 'SANTANDER ATENCIÓN AL CLIENTE',idCuenta: '31'},
      { id: '3201',name: 'DONACIONES',idCuenta: '32'},
      { id: '3301',name: 'UNIQUE ATENCIÓN AL CLIENTE',idCuenta: '33'},
      { id: '3401',name: '122',idCuenta: '34'},
      { id: '3402',name: '123',idCuenta: '34'},
      { id: '3403',name: '127',idCuenta: '34'},
      { id: '3404',name: '123 BO',idCuenta: '34'},
      { id: '3405',name: '123 FRONT',idCuenta: '34'},
      { id: '3407',name: '123 FRONT',idCuenta: '34'},
      { id: '3408',name: 'BO 123',idCuenta: '34'},
      { id: '3409',name: 'BO POTENCIALES',idCuenta: '34'},
      { id: '3410',name: 'BO TELEGESTIÓN',idCuenta: '34'},
      { id: '3411',name: 'CAPTACIÓN RESIDENCIAL',idCuenta: '34'},
      { id: '3412',name: 'ENTRANTES',idCuenta: '34'},
      { id: '3413',name: 'POTENCIALES EMPRESAS',idCuenta: '34'},
      { id: '3414',name: 'POTENCIALES PARTICULARES',idCuenta: '34'},
      { id: '3415',name: 'POTENCIALES SERVIVIO LOWI',idCuenta: '34'},
      { id: '3416',name: 'RETENCIONES',idCuenta: '34'},
      { id: '3501',name: 'COBRANZA',idCuenta: '35'},
      { id: '3601',name: 'ATC BILINGÜE',idCuenta: '36'},
      { id: '3701',name: 'INBOUND, OUTBOUND Y CANALES DIGITALES',idCuenta: '37'},
    ]
  }
  

